# E-SHOP RESTful API

This is a simple API allowing consumers to buy products or add them to their favourites.

## Authors

* **Dinmukhamet Igissinov** - *Initial work* - [Dinmukhamet](https://github.com/Dinmukhamet)


## Acknowledgments

* Hat tip to anyone whose code was used
* Inspiration
* etc

