# Generated by Django 2.2.5 on 2020-01-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField()),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='ProductHitInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchase', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('product_hit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='core.ProductHit')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
