# Generated by Django 2.2.5 on 2020-01-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200131_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='HitInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='core.Hit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
            options={
                'ordering': ['hit'],
            },
        ),
        migrations.RemoveField(
            model_name='producthitinstance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producthitinstance',
            name='product_hit',
        ),
        migrations.DeleteModel(
            name='ProductHit',
        ),
        migrations.DeleteModel(
            name='ProductHitInstance',
        ),
    ]
