# Generated by Django 2.2.5 on 2020-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200131_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitinstance',
            name='hit',
        ),
        migrations.RemoveField(
            model_name='hitinstance',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Hit',
        ),
        migrations.DeleteModel(
            name='HitInstance',
        ),
    ]
