# Generated by Django 2.2.5 on 2020-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200131_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_purchase',
        ),
    ]
