# Generated by Django 2.2.5 on 2020-02-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_total_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_products', to='core.RecommendedProduct')),
            ],
            options={
                'ordering': ['rp'],
            },
        ),
    ]
