# Generated by Django 2.2.5 on 2020-02-01 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_recommendedproduct_recommendedproductinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('products', models.ManyToManyField(to='core.Product')),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.AddField(
            model_name='recommendedproduct',
            name='products',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.DeleteModel(
            name='RecommendedProductInstance',
        ),
    ]
