# Generated by Django 2.2.5 on 2020-02-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
