# Generated by Django 2.2.5 on 2020-02-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200202_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
