# Generated by Django 2.2.5 on 2020-02-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200202_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_purchase',
        ),
    ]
