# Generated by Django 2.2.5 on 2020-02-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_total_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
