# Generated by Django 2.2.5 on 2020-02-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200202_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
