# Generated by Django 2.2.5 on 2020-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200202_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
