# Generated by Django 2.2.5 on 2020-02-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
