# Generated by Django 2.2.5 on 2020-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_hit_total_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
