# Generated by Django 2.2.5 on 2020-02-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200203_0535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hit',
        ),
    ]
