# Generated by Django 2.2.5 on 2020-02-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200204_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_purchase',
        ),
    ]
