# Generated by Django 2.2.5 on 2020-02-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
