# Generated by Django 2.2.5 on 2020-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200209_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
