# Generated by Django 2.2.5 on 2020-02-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200216_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteproduct',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='favouriteproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='favourite',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='FavouriteProduct',
        ),
    ]
