# Generated by Django 2.2.5 on 2020-02-21 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200220_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
