# Generated by Django 2.2.5 on 2020-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200221_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='CustomerInfo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
