# Generated by Django 2.2.5 on 2020-02-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200223_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductToRecommendedProduct',
        ),
    ]
