# Generated by Django 2.2.5 on 2020-02-23 18:00

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200223_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedproduct',
            name='product',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='category', on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]