# Generated by Django 2.2.5 on 2020-02-23 18:12

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200223_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='recommendedproduct',
            name='product',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='category', chained_model_field='category', to='core.Product'),
        ),
    ]