# Generated by Django 2.2.5 on 2020-02-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200223_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedproduct',
            name='product',
        ),
    ]
