# Generated by Django 2.2.5 on 2020-02-25 09:08

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_recommendedproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttosale',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttosale',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
