# Generated by Django 2.2.5 on 2020-02-25 09:15

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200225_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttosale',
            options={'ordering': ['sale']},
        ),
        migrations.RemoveField(
            model_name='producttosale',
            name='product',
        ),
        migrations.AddField(
            model_name='producttosale',
            name='product',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='category', chained_model_field='category', to='core.Product'),
        ),
    ]
