# Generated by Django 2.2.5 on 2020-02-25 14:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200225_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttosale',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='parent_id', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
