# Generated by Django 2.2.5 on 2020-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_producttosalebundle_salebundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSomething',
            field=models.BooleanField(default=True),
        ),
    ]
