# Generated by Django 2.2.5 on 2020-03-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_product_issomething'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isSomething',
        ),
    ]
