# Generated by Django 2.2.5 on 2020-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20200310_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebundle',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
