# Generated by Django 2.2.5 on 2020-03-11 14:25

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_salebundle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='producttosale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='producttosalebundle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recommendedproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='slider',
            name='salebundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SaleBundle'),
        ),
        migrations.AlterField(
            model_name='producttosale',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subcategory', chained_model_field='subcategory', on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AlterField(
            model_name='producttosalebundle',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subcategory', chained_model_field='subcategory', on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AlterField(
            model_name='recommendedproduct',
            name='product',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='subcategory', chained_model_field='subcategory', to='core.Product'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
