# Generated by Django 2.2.5 on 2020-03-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
