# Generated by Django 2.2.5 on 2020-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_producttosalebundle_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('media_type', models.CharField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
