# Generated by Django 2.2.5 on 2020-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_footermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermedia',
            name='image',
            field=models.URLField(default='https://imgur.com/bY5YJhB', max_length=254),
        ),
        migrations.AlterField(
            model_name='footermedia',
            name='media_type',
            field=models.URLField(max_length=254),
        ),
    ]
