# Generated by Django 2.2.5 on 2020-03-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20200318_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['product'], 'verbose_name': 'Коммент к товару', 'verbose_name_plural': 'Коммент к товарам'},
        ),
        migrations.AlterModelOptions(
            name='commentrating',
            options={'ordering': ['comment'], 'verbose_name': 'Рейтинг коммента', 'verbose_name_plural': 'Рейтинг комментов'},
        ),
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'ordering': ['name'], 'verbose_name': 'Данные покупателя', 'verbose_name_plural': 'Данные покупателей'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttosale',
            options={'ordering': ['product'], 'verbose_name': 'Товар по скидке', 'verbose_name_plural': 'Товары по скидке'},
        ),
        migrations.AlterModelOptions(
            name='producttosalebundle',
            options={'ordering': ['salebundle'], 'verbose_name': 'Товар по акции', 'verbose_name_plural': 'Товары по акции'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='purchasedproduct',
            options={'ordering': ['product'], 'verbose_name': 'Купленный товар', 'verbose_name_plural': 'Купленные товары'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['product'], 'verbose_name': 'Рейтинг товара', 'verbose_name_plural': 'Рейтинг товаров'},
        ),
        migrations.AlterModelOptions(
            name='recommendedproduct',
            options={'ordering': ['date_from'], 'verbose_name': 'Рекомендованный товар', 'verbose_name_plural': 'Рекомендованные товары'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['date_from'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='salebundle',
            options={'ordering': ['date_from'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['image'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
