# Generated by Django 2.2.5 on 2020-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20200319_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebundle',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
