# Generated by Django 2.2.5 on 2020-03-21 23:30

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200321_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=core.storage.OverwriteStorage(), upload_to=core.models.upload_location),
        ),
    ]
